NS_SPREADSHEETML    = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
NS_CONTENT_TYPES    = 'http://schemas.openxmlformats.org/package/2006/content-types'
NS_PROPERTIES       = 'http://schemas.openxmlformats.org/officeDocument/2006/extended-properties'
NS_DOC_PROPS_VTYPES = 'http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes'
NS_RELS             = 'http://schemas.openxmlformats.org/package/2006/relationships'
NS_REL_WORKSHEET    = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet'
NS_WORKSHEET_R      = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'
